### ISSUE TITLE
[WebView In App] How to open webview in application?

### ISSUE THREAD

**Issue by njuptzwt** [MixinNetwork/flutter-plugins#135] opened 2022-08-25 02:32 UTC

**Comment by njuptzwt** [comment] 2022-08-25 02:34
How to open webview in application, but not in another window?

**Comment by boyan01** [comment] 2022-11-11 10:59
Sorry the answer is NO, that is impossible now.  Duplicate of #30

You can track this issue for more information. https://github.com/flutter/flutter/issues/37597

**Closed by boyan01** 2022-11-11 10:59 UTC
Labels: desktop_webview_window
