### ISSUE TITLE
[desktop_multi_window] Not working with flutter 3.3 on Windows

### ISSUE THREAD

**Issue by krida2000** [MixinNetwork/flutter-plugins#139] opened 2022-09-02 08:15 UTC
`desktop_multi_window` plugin not working with flutter 3.3 on Windows. To check it you can upgrade flutter and run `example`.

Native exception:
```
Thrown exception at 0x00007FF8B0B0F8F5 (flutter_windows.dll) in desktop_multi_window_example.exe: 0xC0000005: Access violation while reading at address 0x0000000000000008.
```

**Comment by boyan01** [comment] 2022-09-05 03:11
https://github.com/flutter/flutter/issues/110661 seems crash caused by flutter engine.

**Comment by Kingtous** [comment] 2022-09-20 02:07
Same here. I've tested 3.3+, including `dev`, `master`, `beta` channel of flutter. All crash when creating new window.

**Comment by yongyu-wang** [comment] 2022-09-27 06:40
same on 3.3.2 when create new FlutterViewController on windows https://github.com/flutter/flutter/issues/112383
`flutter_controller_ = std::make_unique<flutter::FlutterViewController>(frame.right - frame.left, frame.bottom - frame.top, project)`

**Comment by boyan01** [comment] 2022-11-01 01:50
Seems already fixed in flutter latest master channel.

https://github.com/MixinNetwork/flutter-plugins/issues/151#issuecomment-1297805330

**Comment by boyan01** [comment] 2022-11-01 03:02
tested with flutter master channel. it works now.

**Closed by boyan01** 2022-11-01 03:02 UTC
Labels: bug, desktop_multi_window
