### ISSUE TITLE
[Show WebPage In side App Screen]

### ISSUE THREAD

**Issue by venky9885** [MixinNetwork/flutter-plugins#119] opened 2022-07-10 08:46 UTC
I need to show webview inside app without creating another new window or show the minimized window in front screen

**Comment by boyan01** [comment] 2022-07-14 05:58
duplicate of #62 #30 

It's impossible by using this package now.

You can track this issue for more information. https://github.com/flutter/flutter/issues/37597

**Closed by boyan01** 2022-07-14 05:58 UTC
Labels: duplicate, enhancement, desktop_webview_window
