### ISSUE TITLE
[desktop_webview_window] how use web view as widget on the page?

### ISSUE THREAD

**Issue by majidebraa** [MixinNetwork/flutter-plugins#95] opened 2022-05-07 04:32 UTC
Hello.
How can I use desktop_webview_window as a widget on the page and not pop up?

**Comment by boyan01** [comment] 2022-05-07 06:59
duplicate of #85 #62 #30

No, that is impossible now.  https://github.com/flutter/flutter/issues/37597

**Closed by boyan01** 2022-05-07 06:59 UTC
Labels: duplicate, desktop_webview_window
