### ISSUE TITLE
Will there be any support for webview-window to be supported to be launched without being in a new window

### ISSUE THREAD

**Issue by ninetynin** [MixinNetwork/flutter-plugins#158] opened 2022-11-11 10:26 UTC
Is there any chance that i can launch the url in a same window and not in a new window for https://pub.dev/packages/desktop_webview_window/

**Comment by boyan01** [comment] 2022-11-11 10:58
Sorry the answer is NO, that is impossible now.  Duplicate of #30

You can track this issue for more information. https://github.com/flutter/flutter/issues/37597

**Closed by boyan01** 2022-11-11 10:58 UTC
Labels: desktop_webview_window
