### ISSUE TITLE
[desktop_multi_window] Create child window crash

### ISSUE THREAD

**Issue by Sunshine334419520** [MixinNetwork/flutter-plugins#195] opened 2023-01-06 01:51 UTC
## Reproduce Steps
1. running desktop_multi_window_example
2. Click on 'Create a new World'
3. crash

![image](https://user-images.githubusercontent.com/28834418/210913394-56069790-bf99-48a2-9127-d9732843ebe1.png)

![image](https://user-images.githubusercontent.com/28834418/210913477-b3812e4c-d14e-4782-996e-26902a0cd4f2.png)

**Version :**
 - Flutter Version: [e.g. v3.3.10]
 - OS: [windows 10]
 - plugin: [desktop_multi_window newest]

**Comment by rashcroft7** [comment] 2023-01-11 07:30
I am having the same issue on Windows 10. It runs without issue on Linux (Ubuntu).  I need this to work on Windows, any ideas?

**Comment by boyan01** [comment] 2023-01-13 02:41
It seem the issue duplicated of https://github.com/MixinNetwork/flutter-plugins/issues/139

the crash on Windows caused by flutter engine which has been fixed in latest master channel. see more: https://github.com/flutter/flutter/issues/110311

**Closed** 2023-02-04 01:47 UTC
Labels: platform-windows, desktop_multi_window
