### ISSUE TITLE
[desktop_webview_window] crash on the windows 11

### ISSUE THREAD

**Issue by feimenggo** [MixinNetwork/flutter-plugins#148] opened 2022-09-21 03:38 UTC
### Logs

```
Lost connection to device.
Failed to send request: {"jsonrpc":"2.0","id":"112","method":"resume","params":{"isolateId":"isolates/3882021751716507"}}
```

### Desktop

```
版本	Windows 11 专业版
版本	21H2
安装日期	‎2021/‎11/‎1
操作系统版本	22000.978
体验	Windows 功能体验包 1000.22000.978.0
```

### Video1

https://user-images.githubusercontent.com/12608693/191410201-8fe25fed-ee19-4019-926e-9617fb02c030.mp4

### Video2

https://user-images.githubusercontent.com/12608693/191410992-4c413ec2-7040-479d-8bb6-4e6aa61e80f7.mp4

**Comment by Eee721** [comment] 2022-09-21 11:28
also crash on win10

**Comment by boyan01** [comment] 2022-09-21 13:04
which flutter version are you using?

This carsh may caused by flutter engine. seem more: https://github.com/flutter/flutter/issues/110311

**Comment by feimenggo** [comment] 2022-09-21 14:42
> which flutter version are you using?
> 
> This carsh may caused by flutter engine. see more: [flutter/flutter#110311](https://github.com/flutter/flutter/issues/110311)

```

Doctor summary (to see all details, run flutter doctor -v):
[√] Flutter (Channel stable, 3.3.2, on Microsoft Windows [版本 10.0.22000.978], locale zh-CN)
[√] Android toolchain - develop for Android devices (Android SDK version 29.0.3)
[√] Chrome - develop for the web
[√] Visual Studio - develop for Windows (Visual Studio Community 2022 17.3.3)
[√] Android Studio (version 2021.3)
[√] IntelliJ IDEA Ultimate Edition (version 2021.2)
[√] Connected device (3 available)
[√] HTTP Host Availability

```

**Comment by jinnyum** [comment] 2022-09-26 05:22
Can't predict when i'll be able to use it again?

**Comment by bhlin790** [comment] 2022-09-27 09:23
Windows 10 also crashed

**Comment by wanggw2022** [comment] 2022-10-21 01:05
Modify the file webview_ window.cc

// Create the title bar view.
  /*
  std::vector<std::string> args = {"web_view_title_bar", std::to_string(window_id_)};
  flutter_action_bar_ = std::make_unique<webview_window::FlutterView>(std::move(args));
  auto title_bar_handle = flutter_action_bar_->GetWindow();
  SetParent(title_bar_handle, hwnd_.get());
  MoveWindow(title_bar_handle, 0, 0, rc.right - rc.left, title_bar_height, true);
  ShowWindow(title_bar_handle, SW_SHOW);

  assert(hwnd_ != nullptr);

  ShowWindow(hwnd_.get(), SW_SHOW);
  UpdateWindow(hwnd_.get());
   */

**Comment by b4ra0** [comment] 2022-10-27 20:05
#152

**Comment by boyan01** [comment] 2022-11-01 01:50
Seems already fixed in flutter latest master channel.

https://github.com/MixinNetwork/flutter-plugins/issues/151#issuecomment-1297805330

**Comment by boyan01** [comment] 2022-11-01 02:56
tested, it now works in flutter master channel.

**Closed by boyan01** 2022-11-01 02:56 UTC
Labels: platform-windows, desktop_webview_window
