### ISSUE TITLE
Can embedded in one window not open a new window for macos ?

### ISSUE THREAD

**Issue by sugur** [MixinNetwork/flutter-plugins#167] opened 2022-11-28 05:49 UTC
Can embedded in one window not open a new window for macos ?

**Comment by boyan01** [comment] 2022-12-05 08:07
I guess you means the `desktop_webview_window` plugin

Sorry the answer is NO, that is impossible now. Duplicate of https://github.com/MixinNetwork/flutter-plugins/issues/30

You can track this issue for more information. https://github.com/flutter/flutter/issues/37597

**Closed by boyan01** 2022-12-05 08:07 UTC
Labels: desktop_webview_window, desktop_multi_window

**Comment by boyan01** [comment] 2022-12-05 08:09
the macos version is tracked here: https://github.com/flutter/flutter/issues/41725

**Comment by sugur** [comment] 2022-12-05 15:11
> I guess you means the `desktop_webview_window` plugin
> 
> Sorry the answer is NO, that is impossible now. Duplicate of #30
> 
> You can track this issue for more information. [flutter/flutter#37597](https://github.com/flutter/flutter/issues/37597)

Yes, but `desktop_webview_window` plugin cannot setup user_agent and set javsscript.
